exclude: '^(\.vscode|\.idea|\.vs)/'
repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      sha: v2.2.3
      hooks:
          - id: trailing-whitespace
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: end-of-file-fixer
    - repo: https://github.com/syntaqx/git-hooks
      rev: v0.0.16
      hooks:
          - id: go-fmt
