language: go

env:
  - GO111MODULE=on

before_script:
  - pushd .. ; go get golang.org/x/lint/golint ; popd
  - curl https://pre-commit.com/install-local.py | python -
  - pre-commit run --all-files

go:
  - stable
